# template.yaml
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 256
    Layers:
      - !Ref MyModuleLayer
      - !Ref NodeModuleLayer
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDB
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowCredentials: false
      AllowMethods: "'POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

Resources:
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  NodeModuleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      LayerName: "NodeModuleLayer"
      ContentUri: layers/npm
  MyModuleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      LayerName: "MyModuleLayer"
      ContentUri: layers/common_layer

  UsersGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/users/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /users
            Method: GET
            RestApiId:
              Ref: CommonAPI

  UserGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/user/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /user
            Method: GET
            RestApiId:
              Ref: CommonAPI

  UserPostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/user/post
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /user
            Method: POST
            RestApiId:
              Ref: CommonAPI

  UserUserIdGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/user/user_id/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /user/{user_id}
            Method: GET
            RestApiId:
              Ref: CommonAPI

  UserUserIdPutLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/user/user_id/put
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /user/{user_id}
            Method: PUT
            RestApiId:
              Ref: CommonAPI

  AfterSchoolGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolPostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/post
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school
            Method: POST
            RestApiId:
              Ref: CommonAPI

  AfterSchoolSchoolIdPutLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/put
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}
            Method: PUT
            RestApiId:
              Ref: CommonAPI

  AfterSchoolSchoolIdGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/get
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorPostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/post
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: POST
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorPutLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/put
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: PUT
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorDeleteLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/delete
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: DELETE
            RestApiId:
              Ref: CommonAPI

  MonthlyGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/monthly/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /monthly
            Method: GET
            RestApiId:
              Ref: CommonAPI

  MonthlyDailyGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/monthly/daily/get
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /monthly/daily
            Method: GET
            RestApiId:
              Ref: CommonAPI

  MonthlyDailyPostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/monthly/daily/post
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /monthly/daily
            Method: POST
            RestApiId:
              Ref: CommonAPI

  CommonAPI: # API Gateway
    Type: AWS::Serverless::Api
    Properties:
      Name: arinko_api
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Origin, X-Requested-With, Content-Type, Authorization, Accept'"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api-v1-oas30-apigateway.yaml
      OpenApiVersion: 3.0.1
      StageName: development
      EndpointConfiguration: REGIONAL