# template.yaml
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Layers:
      - !Ref MyModuleLayer
      - !Ref NodeModuleLayer
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowCredentials: true
      AllowMethods: "'POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

Resources:
  NodeModuleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      LayerName: "NodeModuleLayer"
      ContentUri: layers/npm
  MyModuleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      LayerName: "MyModuleLayer"
      ContentUri: layers/common_layer

  UserGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/user/get
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /user
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/get
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolSchoolIdGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/get
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/get
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: GET
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorPostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/post
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: POST
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorPutLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/put
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: PUT
            RestApiId:
              Ref: CommonAPI

  AfterSchoolInstructorDeleteLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/after_school/school_id/instructors/delete
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /after_school/{school_id}/instructors
            Method: DELETE
            RestApiId:
              Ref: CommonAPI

  MonthlyGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/monthly/get
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /monthly
            Method: GET
            RestApiId:
              Ref: CommonAPI

  MonthlyDailyGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/monthly/daily/get
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /monthly/daily
            Method: GET
            RestApiId:
              Ref: CommonAPI

  MonthlyDailyPostLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler/monthly/daily/post
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /monthly/daily
            Method: POST
            RestApiId:
              Ref: CommonAPI

  CommonAPI: # API Gateway
    Type: AWS::Serverless::Api
    Properties:
      Name: arinko_api
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Origin, X-Requested-With, Content-Type, Authorization, Accept'"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api-v1-oas30-apigateway.yaml
      OpenApiVersion: 3.0.1
      StageName: development
      EndpointConfiguration: REGIONAL